apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spoiler
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
    path: /metrics
  kafka:
    pool: {{kafkaPool}}
  secureLogs:
    enabled: true