apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spoiler
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
  readiness:
    path: isready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: false
    path: /metrics
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: spurtedu
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        databases:
          - name: spoiler
            envVarPrefix: DATABASE
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spoiler-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
