apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spoiler
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 10
  readiness:
    path: isready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: spurtedu
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: db-custom-1-3840
        databases:
          - name: spoiler
            envVarPrefix: DATABASE
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spoiler-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
